version: '3.8'
volumes:
  postgres_data:
  static_files:
  media_files:
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
      
  web:
    image: antwillow/yamdb:latest
    restart: always
    volumes:
      - static_files:/code/static
      - media_files:/code/media
    depends_on:
      - db
    env_file:
      - ./.env
      
  nginx:
    image: nginx:1.19
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_files:/code/static
      - media_files:/code/media
    environment:
      - NGINX_HOST=${HOST}
    depends_on:
      - web
    